spring.application.name=paymentservice
server.port=8086

spring.datasource.url=jdbc:postgresql://localhost:5432/payment1_db
spring.datasource.username=postgres
spring.datasource.password=R1a2k3s4*

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
management.endpoints.web.exposure.include=*
