# ===============================
# SERVER CONFIG
# ===============================
server.port=8087

spring.application.name=rewardservice

# ===============================
# DATABASE CONFIG (POSTGRESQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/reward_db
spring.datasource.username=postgres
spring.datasource.password=R1a2k3s4*
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Optional but good for debugging
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ===============================
# EUREKA CONFIG
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.instance.prefer-ip-address=true

# ===============================
# JWT SECURITY CONFIG
# ===============================
spring.security.oauth2.resourceserver.jwt.secret-key=your-very-secret-key-your-very-secret-key

eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
# ===============================
# LOGGING (OPTIONAL BUT USEFUL)
# ===============================
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG